version: '3'
services:

  db:
    container_name: "db"
    restart: always
    image: postgres:latest
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - db:/var/lib/postgresql
    env_file:
      - ../.env

volumes:
  db: